/**
 * ZAM Club - Mock Data
 * All application data as JS objects/arrays
 * Ready for Supabase integration: replace with API calls
 */

// Current logged-in user
const currentUser = {
  id: 'usr_001',
  name: 'Max Müller',
  username: '@maxmueller',
  email: 'max.mueller@example.de',
  memberSince: '2023-03-15',
  memberSinceFormatted: 'Mitglied seit März 2023',
  points: 1247,
  level: 'Gold Member',
  avatar: null,
  initials: 'MM',
  stats: {
    visits: 34,
    eventsAttended: 8,
    dealsUsed: 21,
  },
};

// Badges
const badges = [
  {
    id: 'badge_001',
    name: 'Erster Besuch',
    icon: '🏆',
    description: 'Dein erster Besuch im ZAM!',
    earned: true,
    earnedDate: '2023-03-15',
    color: '#f59e0b',
  },
  {
    id: 'badge_002',
    name: 'Super Fan',
    icon: '⭐',
    description: '10 Besuche absolviert',
    earned: true,
    earnedDate: '2023-05-20',
    color: '#7c3aed',
  },
  {
    id: 'badge_003',
    name: 'Deal Hunter',
    icon: '🎯',
    description: '10 Deals eingelöst',
    earned: true,
    earnedDate: '2023-07-11',
    color: '#10b981',
  },
  {
    id: 'badge_004',
    name: 'Community Star',
    icon: '💬',
    description: '5 Beiträge in der Community',
    earned: true,
    earnedDate: '2023-09-03',
    color: '#3b82f6',
  },
  {
    id: 'badge_005',
    name: 'Treue Seele',
    icon: '❤️',
    description: '1 Jahr Mitglied',
    earned: false,
    earnedDate: null,
    color: '#ef4444',
  },
];

// Events
const events = [
  {
    id: 'evt_001',
    title: 'Fitness Morning – Yoga im Atrium',
    category: 'Sport',
    categoryColor: '#10b981',
    dateFormatted: 'Mi, 18. Juni 2026',
    time: '09:00 – 10:30 Uhr',
    location: 'Atrium, EG',
    description: 'Starte energetisch in den Tag mit einer Yoga-Session mitten im Einkaufszentrum. Für alle Levels geeignet – Matte mitbringen!',
    spotsTotal: 30,
    spotsLeft: 7,
    pointsReward: 50,
    isFeatured: true,
    isJoined: false,
  },
  {
    id: 'evt_002',
    title: 'Street Food Festival',
    category: 'Food & Drinks',
    categoryColor: '#f59e0b',
    dateFormatted: 'Sa, 21. Juni 2026',
    time: '11:00 – 20:00 Uhr',
    location: 'Außenbereich West',
    description: 'Internationale Küche, lokale Köstlichkeiten und Live-Cooking-Shows. Über 15 Food-Trucks warten auf euch!',
    spotsTotal: 500,
    spotsLeft: 312,
    pointsReward: 75,
    isFeatured: true,
    isJoined: false,
  },
  {
    id: 'evt_003',
    title: 'Kids Workshop: Basteln & Malen',
    category: 'Familie',
    categoryColor: '#ec4899',
    dateFormatted: 'Do, 25. Juni 2026',
    time: '14:00 – 16:00 Uhr',
    location: 'Kinderparadies, OG 1',
    description: 'Kreative Nachmittagsgestaltung für Kinder von 4–10 Jahren. Material wird gestellt. Anmeldung erforderlich.',
    spotsTotal: 20,
    spotsLeft: 5,
    pointsReward: 30,
    isFeatured: false,
    isJoined: false,
  },
  {
    id: 'evt_004',
    title: 'Live Musik: Summer Vibes',
    category: 'Musik',
    categoryColor: '#7c3aed',
    dateFormatted: 'So, 28. Juni 2026',
    time: '15:00 – 18:00 Uhr',
    location: 'Hauptbühne, EG',
    description: 'Genieße entspannte Summer-Beats von lokalen Künstlern. Eintritt frei – einfach vorbeikommen und genießen!',
    spotsTotal: 200,
    spotsLeft: 150,
    pointsReward: 40,
    isFeatured: false,
    isJoined: false,
  },
];

// Deals
const deals = [
  {
    id: 'deal_001',
    storeName: 'Café Aroma',
    storeIcon: '☕',
    category: 'Food & Drinks',
    categoryColor: '#f59e0b',
    discount: '20%',
    title: '20% auf alle Heißgetränke',
    description: 'Gültig auf Kaffee, Cappuccino, Latte und alle Tee-Spezialitäten.',
    expiryFormatted: 'Gültig bis 30. Juni 2026',
    pointsReward: 15,
    isHot: true,
    isClaimed: false,
    barcode: '1234-5678-9012',
  },
  {
    id: 'deal_002',
    storeName: 'FashionHub',
    storeIcon: '👗',
    category: 'Mode',
    categoryColor: '#ec4899',
    discount: '15%',
    title: '15% Rabatt auf Sommerkollektion',
    description: 'Auf die gesamte Sommerkollektion 2026 – Damen, Herren und Kinder.',
    expiryFormatted: 'Gültig bis 15. Juli 2026',
    pointsReward: 25,
    isHot: false,
    isClaimed: false,
    barcode: '2345-6789-0123',
  },
  {
    id: 'deal_003',
    storeName: 'Trattoria Bella',
    storeIcon: '🍕',
    category: 'Restaurant',
    categoryColor: '#ef4444',
    discount: '2+1',
    title: '2 Pizzen kaufen, 1 gratis',
    description: 'Günstigste Pizza gratis bei Kauf von zwei Pizzen. Gültig Di–Do, vor 18 Uhr.',
    expiryFormatted: 'Gültig bis 22. Juni 2026',
    pointsReward: 30,
    isHot: true,
    isClaimed: false,
    barcode: '3456-7890-1234',
  },
  {
    id: 'deal_004',
    storeName: 'Buchreich',
    storeIcon: '📚',
    category: 'Bücher',
    categoryColor: '#3b82f6',
    discount: '10%',
    title: '10% auf Bestseller',
    description: 'Auf alle Spiegel-Bestseller des Monats Juni.',
    expiryFormatted: 'Gültig bis 30. Juni 2026',
    pointsReward: 10,
    isHot: false,
    isClaimed: false,
    barcode: '4567-8901-2345',
  },
  {
    id: 'deal_005',
    storeName: 'FitZone',
    storeIcon: '💪',
    category: 'Sport & Fitness',
    categoryColor: '#10b981',
    discount: '1 Monat',
    title: '1 Monat gratis Probetraining',
    description: 'Teste alle Geräte, Kurse und Wellness-Bereiche gratis für einen Monat.',
    expiryFormatted: 'Gültig bis 31. Juli 2026',
    pointsReward: 100,
    isHot: true,
    isClaimed: false,
    barcode: '5678-9012-3456',
  },
];

// Merchants
const merchants = [
  {
    id: 'mer_001',
    name: 'Café Aroma',
    icon: '☕',
    category: 'Café & Bäckerei',
    location: 'EG, Shop 12',
    hours: 'Mo–Sa 08:00–20:00, So 09:00–18:00',
    phone: '+49 89 12345678',
    description: 'Ihr Wohlfühl-Café im ZAM mit hausgemachten Kuchen, fair-trade Kaffee und einem warmen Lächeln.',
    currentPromo: '20% auf alle Heißgetränke',
    promoColor: '#f59e0b',
    isOpen: true,
    rating: 4.8,
    reviewCount: 247,
    tags: ['Frühstück', 'Mittagsmenü', 'Kuchen', 'Vegetarisch'],
    isExpanded: false,
  },
  {
    id: 'mer_002',
    name: 'FashionHub',
    icon: '👗',
    category: 'Mode & Accessoires',
    location: 'OG 1, Shop 34',
    hours: 'Mo–Sa 10:00–20:00',
    phone: '+49 89 23456789',
    description: 'Trendige Mode für die ganze Familie – von Casual bis Formal, von Urban bis Classic.',
    currentPromo: '15% Sommerrabatt',
    promoColor: '#ec4899',
    isOpen: true,
    rating: 4.5,
    reviewCount: 183,
    tags: ['Damen', 'Herren', 'Kinder', 'Sale'],
    isExpanded: false,
  },
  {
    id: 'mer_003',
    name: 'Trattoria Bella',
    icon: '🍕',
    category: 'Restaurant',
    location: 'Food Court, OG 2',
    hours: 'Mo–So 11:00–22:00',
    phone: '+49 89 34567890',
    description: 'Authentische italienische Küche mit frischen Zutaten. Selbstgemachte Pasta, knusprige Pizza aus dem Steinofen.',
    currentPromo: '2+1 Pizza-Aktion',
    promoColor: '#ef4444',
    isOpen: true,
    rating: 4.7,
    reviewCount: 312,
    tags: ['Pizza', 'Pasta', 'Vegetarisch', 'Familienfreundlich'],
    isExpanded: false,
  },
  {
    id: 'mer_004',
    name: 'FitZone',
    icon: '💪',
    category: 'Sport & Wellness',
    location: 'OG 3, gesamte Etage',
    hours: 'Mo–Fr 06:00–22:00, Sa–So 08:00–20:00',
    phone: '+49 89 45678901',
    description: 'Modernster Fitnessbereich mit über 150 Geräten, Gruppenklassen, Sauna und Wellnessbereich.',
    currentPromo: '1 Monat gratis testen',
    promoColor: '#10b981',
    isOpen: true,
    rating: 4.6,
    reviewCount: 428,
    tags: ['Gym', 'Yoga', 'Sauna', 'Personal Training'],
    isExpanded: false,
  },
];

// Community posts
const communityPosts = [
  {
    id: 'post_001',
    author: { name: 'Lisa K.', initials: 'LK', avatarColor: '#7c3aed', level: 'Gold Member' },
    content: 'Das Street Food Festival war absolut der Hammer! Die koreanischen Tteokbokki vom letzten Jahr haben mich nicht losgelassen – hoffe dieses Jahr sind die auch wieder da 🔥',
    timeAgo: 'vor 2 Stunden',
    likes: 24,
    comments: 5,
    isLiked: false,
    tags: ['StreetFood', 'ZAMFestival'],
  },
  {
    id: 'post_002',
    author: { name: 'Thomas R.', initials: 'TR', avatarColor: '#10b981', level: 'Silber Member' },
    content: 'Heute beim Yoga-Kurs mitgemacht – was für ein tolles Erlebnis direkt im Atrium! Die Atmosphäre war unglaublich. Nächste Woche bin ich auf jeden Fall wieder dabei. 🧘‍♂️',
    timeAgo: 'vor 6 Stunden',
    likes: 18,
    comments: 3,
    isLiked: false,
    tags: ['Yoga', 'Fitness', 'ZAMLife'],
  },
  {
    id: 'post_003',
    author: { name: 'Sarah M.', initials: 'SM', avatarColor: '#ec4899', level: 'Platin Member' },
    content: 'Den FitZone Gutschein (1 Monat gratis) eingelöst und schon am ersten Tag bereut – bereut dass ich nicht früher angefangen habe! Die Anlage ist top, Personal super freundlich. 💪',
    timeAgo: 'gestern',
    likes: 41,
    comments: 9,
    isLiked: true,
    tags: ['FitZone', 'Deals', 'Empfehlung'],
  },
  {
    id: 'post_004',
    author: { name: 'Michael B.', initials: 'MB', avatarColor: '#f59e0b', level: 'Gold Member' },
    content: 'Hat jemand die neue Sommerkollektion bei FashionHub gesehen? Die Auswahl ist dieses Jahr wirklich stark! Mit dem 15%-Deal ein echtes Schnäppchen gemacht 🛍️',
    timeAgo: 'gestern',
    likes: 12,
    comments: 2,
    isLiked: false,
    tags: ['Fashion', 'Shopping', 'ZAMDeals'],
  },
  {
    id: 'post_005',
    author: { name: 'Anna W.', initials: 'AW', avatarColor: '#3b82f6', level: 'Silber Member' },
    content: 'Kids Workshop letzten Donnerstag – meine Tochter (7) hatte eine Riesenfreude! Die Betreuer waren so geduldig und kreativ. Absolute Empfehlung für Familien ⭐',
    timeAgo: 'vor 3 Tagen',
    likes: 33,
    comments: 7,
    isLiked: false,
    tags: ['Kids', 'Familie', 'Workshop'],
  },
];

// Spin wheel rewards
const spinRewards = [
  { label: '50 Punkte', points: 50, probability: 0.30 },
  { label: '25 Punkte', points: 25, probability: 0.35 },
  { label: '100 Punkte', points: 100, probability: 0.15 },
  { label: '10 Punkte', points: 10, probability: 0.15 },
  { label: '200 Punkte', points: 200, probability: 0.04 },
  { label: 'Jackpot! 500P', points: 500, probability: 0.01 },
];

// Global app data namespace
// Supabase migration: replace these with supabase.from('table').select()
window.ZAMData = {
  currentUser,
  badges,
  events,
  deals,
  merchants,
  communityPosts,
  spinRewards,
};
