/**
 * ZAM Club — Demo-Datenlayer (Präsentations-Version)
 * ============================================================
 * Realistische Inhalte für das ZAM Freiham (München-West).
 * Alle Feldnamen in snake_case — Supabase-ready.
 *
 * Supabase-Migration:
 *   1. Tabellen anlegen (SQL in /supabase/schema.sql)
 *   2. Diese Dateien durch API-Calls ersetzen:
 *      const { data } = await supabase.from('events').select('*')
 *   3. window.ZAMData.* durch die API-Responses ersetzen
 * ============================================================
 */

'use strict';

// ============================================================
// TABLE: profiles
// Supabase: auth.users (id) → public.profiles (user_id)
// ============================================================
const profiles = [
  {
    id:                      'usr_001',
    user_id:                 'usr_001',
    display_name:            'Julia Maier',
    username:                '@juliamaier',
    email:                   'julia.maier@example.de',
    avatar_url:              null,
    initials:                'JM',
    member_since:            '2024-03-10',
    member_since_formatted:  'Mitglied seit März 2024',
    level:                   'gold',
    points:                  2460,
    stats: {
      visits:           63,
      events_attended:  18,
      deals_used:       41,
    },
  },
];

const currentUser = profiles[0];

// ============================================================
// TABLE: badges
// Supabase: public.badges
// ============================================================
const badges = [
  {
    id:          'badge_001',
    name:        'Erster Besuch',
    icon:        '🏆',
    description: 'Herzlich willkommen im ZAM Freiham!',
    color:       '#f59e0b',
    earned:      true,
    earned_date: '2024-03-10',
  },
  {
    id:          'badge_002',
    name:        'Stammgast',
    icon:        '⭐',
    description: '10 Besuche im ZAM',
    color:       '#7c3aed',
    earned:      true,
    earned_date: '2024-06-05',
  },
  {
    id:          'badge_003',
    name:        'Deal Hunter',
    icon:        '🎯',
    description: '10 Deals erfolgreich eingelöst',
    color:       '#10b981',
    earned:      true,
    earned_date: '2024-08-22',
  },
  {
    id:          'badge_004',
    name:        'Community Star',
    icon:        '💬',
    description: '5 Beiträge in der Community geteilt',
    color:       '#3b82f6',
    earned:      true,
    earned_date: '2024-10-14',
  },
  {
    id:          'badge_005',
    name:        'Freiham Urgestein',
    icon:        '🏘️',
    description: '1 Jahr treues ZAM-Club-Mitglied',
    color:       '#ef4444',
    earned:      false,
    earned_date: null,
  },
  {
    id:          'badge_006',
    name:        'Spin Master',
    icon:        '🎰',
    description: '7 Tage in Folge am Glücksrad gedreht',
    color:       '#a855f7',
    earned:      false,
    earned_date: null,
  },
  {
    id:          'badge_007',
    name:        'Event-Enthusiast',
    icon:        '🎟️',
    description: 'An 5 ZAM-Events teilgenommen',
    color:       '#f59e0b',
    earned:      false,
    earned_date: null,
  },
  {
    id:          'badge_008',
    name:        'Platin-Star',
    icon:        '💎',
    description: '3.000 Punkte gesammelt',
    color:       '#c084fc',
    earned:      false,
    earned_date: null,
  },
  {
    id:          'badge_009',
    name:        'Foodie',
    icon:        '🍕',
    description: '5 Food & Drinks Deals eingelöst',
    color:       '#f97316',
    earned:      false,
    earned_date: null,
  },
  {
    id:          'badge_010',
    name:        'Check-in König',
    icon:        '📍',
    description: '20× im ZAM eingecheckt',
    color:       '#06b6d4',
    earned:      false,
    earned_date: null,
  },
];

// ============================================================
// TABLE: merchants
// Supabase: public.merchants
// ============================================================
const merchants = [
  {
    id:             'mer_001',
    name:           'Café Müller',
    icon:           '☕',
    category:       'Café & Bäckerei',
    category_color: '#f59e0b',
    location:       'EG, Eingang West',
    floor:          'EG',
    hours:          'Mo–Sa 07:30–20:00, So 09:00–18:00',
    phone:          '+49 89 4521-0110',
    description:    'Das gemütliche Herzstück des ZAM. Frische Backwaren, handgefertigte Kaffeespezialitäten und ein großer Außensitzbereich.',
    current_promo:  'Gratis Kaffee zum Stück Kuchen',
    promo_color:    '#f59e0b',
    is_open:        true,
    rating:         4.8,
    review_count:   312,
    tags:           ['Frühstück', 'Kaffee', 'Kuchen', 'Terrasse'],
  },
  {
    id:             'mer_002',
    name:           'KFC',
    icon:           '🍗',
    category:       'Fast Food',
    category_color: '#dc2626',
    location:       'Food Court, OG 1',
    floor:          'OG 1',
    hours:          'Mo–So 10:00–22:00',
    phone:          '+49 89 4521-0202',
    description:    'Kentucky Fried Chicken – knusprige Chicken-Klassiker, Burger, Twister und mehr. Der Klassiker für Chicken-Fans.',
    current_promo:  '2 Hot Wings gratis ab 10 €',
    promo_color:    '#dc2626',
    is_open:        true,
    rating:         4.1,
    review_count:   284,
    tags:           ['Chicken', 'Burger', 'Fast Food', 'Family'],
  },
  {
    id:             'mer_003',
    name:           'Deichmann',
    icon:           '👟',
    category:       'Schuhe & Accessoires',
    category_color: '#2563eb',
    location:       'EG, Shop 07',
    floor:          'EG',
    hours:          'Mo–Sa 09:30–20:00',
    phone:          '+49 89 4521-0307',
    description:    'Europas größter Schuhhändler – Trends für die ganze Familie zu fairen Preisen. Damen, Herren, Kinder.',
    current_promo:  '2. Paar 50 % günstiger',
    promo_color:    '#2563eb',
    is_open:        true,
    rating:         4.3,
    review_count:   198,
    tags:           ['Damen', 'Herren', 'Kinder', 'Sportschuhe'],
  },
  {
    id:             'mer_004',
    name:           'Matratzen Concord',
    icon:           '🛏️',
    category:       'Wohnen & Schlafen',
    category_color: '#7c3aed',
    location:       'OG 1, Shop 12',
    floor:          'OG 1',
    hours:          'Mo–Sa 10:00–19:30',
    phone:          '+49 89 4521-0412',
    description:    'Experten für erholsamen Schlaf. Große Auswahl an Matratzen, Lattenrosten und Bettwaren mit kostenloser Schlafberatung.',
    current_promo:  'Gratis Schlafberatung + 10% Club-Rabatt',
    promo_color:    '#7c3aed',
    is_open:        true,
    rating:         4.5,
    review_count:   127,
    tags:           ['Matratzen', 'Schlafen', 'Beratung', 'Boxspringbett'],
  },
  {
    id:             'mer_005',
    name:           'Beautystudio',
    icon:           '💅',
    category:       'Beauty & Wellness',
    category_color: '#ec4899',
    location:       'OG 1, Shop 05',
    floor:          'OG 1',
    hours:          'Mo–Sa 10:00–20:00',
    phone:          '+49 89 4521-0505',
    description:    'Kosmetik, Nails, Wimpernverlängerung und Skincare-Beratung. Dein Wohlfühlort im ZAM für den perfekten Look.',
    current_promo:  '20% auf Naildesign für Club-Mitglieder',
    promo_color:    '#ec4899',
    is_open:        true,
    rating:         4.7,
    review_count:   163,
    tags:           ['Nails', 'Kosmetik', 'Wimpern', 'Skincare'],
  },
  {
    id:             'mer_006',
    name:           'Woolworth',
    icon:           '🛒',
    category:       'Drogerie & Haushalt',
    category_color: '#ea580c',
    location:       'EG, Shop 02',
    floor:          'EG',
    hours:          'Mo–Sa 09:00–20:00',
    phone:          '+49 89 4521-0602',
    description:    'Alles für den Alltag: Drogerieartikel, Haushaltswaren, Textilien, Süßigkeiten und Saisonware zu kleinen Preisen.',
    current_promo:  '3 für 2 auf Süßwaren',
    promo_color:    '#ea580c',
    is_open:        true,
    rating:         4.0,
    review_count:   211,
    tags:           ['Drogerie', 'Haushalt', 'Textilien', 'Günstig'],
  },
  {
    id:             'mer_007',
    name:           'ApoPark Apotheke',
    icon:           '💊',
    category:       'Gesundheit',
    category_color: '#06b6d4',
    location:       'EG, Shop 03',
    floor:          'EG',
    hours:          'Mo–Sa 08:00–20:00',
    phone:          '+49 89 4521-0703',
    description:    'Ihre Apotheke im ZAM mit kompetenter Beratung, breitem Naturkosmetik-Sortiment und kostenlosem Blutdruck-Check jeden Mittwoch.',
    current_promo:  'Sonnenschutz-Set 3 für 2',
    promo_color:    '#06b6d4',
    is_open:        true,
    rating:         4.8,
    review_count:   247,
    tags:           ['Apotheke', 'Naturkosmetik', 'Beratung', 'Gesundheit'],
  },
  {
    id:             'mer_008',
    name:           'Dunkin Donuts',
    icon:           '🍩',
    category:       'Café & Snacks',
    category_color: '#f97316',
    location:       'EG, Eingang Ost',
    floor:          'EG',
    hours:          'Mo–So 07:00–21:00',
    phone:          '+49 89 4521-0801',
    description:    'Donuts in über 50 Sorten, frischer Kaffee und Snacks für jeden Geschmack. Für süße Momente zwischendurch.',
    current_promo:  'Gratis Donut zum Kaffee',
    promo_color:    '#f97316',
    is_open:        true,
    rating:         4.4,
    review_count:   339,
    tags:           ['Donuts', 'Kaffee', 'Snacks', 'Süßes'],
  },
  {
    id:             'mer_009',
    name:           'Service Direct',
    icon:           '🔧',
    category:       'Services',
    category_color: '#64748b',
    location:       'EG, Shop 04',
    floor:          'EG',
    hours:          'Mo–Sa 10:00–19:00',
    phone:          '+49 89 4521-0904',
    description:    'Reparatur, Schlüsseldienst, Handyreparatur, Schuhservice und mehr – alles unter einem Dach im ZAM.',
    current_promo:  '10% auf Handyreparatur für Club-Mitglieder',
    promo_color:    '#64748b',
    is_open:        true,
    rating:         4.6,
    review_count:   94,
    tags:           ['Reparatur', 'Schlüssel', 'Handy', 'Service'],
  },
  {
    id:             'mer_010',
    name:           'Smyths Toys',
    icon:           '🧸',
    category:       'Spielzeug & Familie',
    category_color: '#16a34a',
    location:       'OG 2, gesamte Etage',
    floor:          'OG 2',
    hours:          'Mo–Sa 09:30–20:00',
    phone:          '+49 89 4521-1020',
    description:    'Europas größtes Spielzeug-Erlebnis: Lego, Gaming, Outdoor-Spaß, Babyausstattung und interaktive Spielbereiche für Kinder.',
    current_promo:  '15% auf LEGO für Club-Mitglieder',
    promo_color:    '#16a34a',
    is_open:        true,
    rating:         4.7,
    review_count:   421,
    tags:           ['Spielzeug', 'LEGO', 'Gaming', 'Baby', 'Kinder'],
  },
  {
    id:             'mer_011',
    name:           'REWE',
    icon:           '🛍️',
    category:       'Supermarkt',
    category_color: '#dc2626',
    location:       'EG, Haupteingang',
    floor:          'EG',
    hours:          'Mo–Sa 07:00–22:00',
    phone:          '+49 89 4521-1101',
    description:    'Ihr REWE im ZAM mit vollständigem Sortiment, frischer Brottheke, Bio-Auswahl und breitem Getränkesortiment.',
    current_promo:  '50 Punkte bei Einkauf über 30 €',
    promo_color:    '#dc2626',
    is_open:        true,
    rating:         4.3,
    review_count:   508,
    tags:           ['Supermarkt', 'Bio', 'Bäckerei', 'Getränke'],
  },
  {
    id:             'mer_012',
    name:           "Pit's Stop Burger",
    icon:           '🍔',
    category:       'Burger & Fast Food',
    category_color: '#b45309',
    location:       'Food Court, OG 1',
    floor:          'OG 1',
    hours:          'Mo–So 11:00–22:00',
    phone:          '+49 89 4521-1212',
    description:    'Handgemachte Smash-Burger mit frischen Patties, hausgemachten Saucen und belgischen Pommes. Regionalität trifft Burgerperfection.',
    current_promo:  '2 Menüs für 18 €',
    promo_color:    '#b45309',
    is_open:        true,
    rating:         4.8,
    review_count:   317,
    tags:           ['Burger', 'Smash', 'Pommes', 'Craft'],
  },
  {
    id:             'mer_013',
    name:           'Subway',
    icon:           '🥖',
    category:       'Fast Food',
    category_color: '#15803d',
    location:       'Food Court, OG 1',
    floor:          'OG 1',
    hours:          'Mo–So 09:00–22:00',
    phone:          '+49 89 4521-1301',
    description:    'Frische Subs nach Wahl – Brot, Belag und Zutaten selbst zusammenstellen. Viele vegane und vegetarische Optionen.',
    current_promo:  'Sub des Tages 6,49 € für Club-Mitglieder',
    promo_color:    '#15803d',
    is_open:        true,
    rating:         4.0,
    review_count:   196,
    tags:           ['Subs', 'Salat', 'Vegan', 'Fresh'],
  },
  {
    id:             'mer_014',
    name:           'Sunhye',
    icon:           '🌸',
    category:       'Asiatische Küche',
    category_color: '#db2777',
    location:       'Food Court, OG 1',
    floor:          'OG 1',
    hours:          'Mo–So 11:00–21:30',
    phone:          '+49 89 4521-1401',
    description:    'Koreanisch-japanische Fusionsküche: Bibimbap, Sushi-Bowls, Miso-Suppen und hausgemachte Kimchi-Beilagen.',
    current_promo:  'Gratis Miso-Suppe zur Bowl',
    promo_color:    '#db2777',
    is_open:        true,
    rating:         4.7,
    review_count:   204,
    tags:           ['Koreanisch', 'Japanisch', 'Bowl', 'Vegan'],
  },
  {
    id:             'mer_015',
    name:           'Asia Street Food',
    icon:           '🥢',
    category:       'Asiatische Küche',
    category_color: '#065f46',
    location:       'Food Court, OG 1',
    floor:          'OG 1',
    hours:          'Mo–So 11:00–21:30',
    phone:          '+49 89 4521-1501',
    description:    'Authentisches Asia Street Food: Pad Thai, Wok-Gerichte, hausgemachte Frühlingsrollen und frische Currys aus Thailand, Vietnam und China.',
    current_promo:  'Gratis Frühlingsrollen zum Hauptgericht',
    promo_color:    '#065f46',
    is_open:        true,
    rating:         4.6,
    review_count:   281,
    tags:           ['Thai', 'Vietnamesisch', 'Wok', 'Vegan'],
  },
  {
    id:             'mer_016',
    name:           'Takko',
    icon:           '👕',
    category:       'Mode & Textilien',
    category_color: '#4f46e5',
    location:       'EG, Shop 09',
    floor:          'EG',
    hours:          'Mo–Sa 09:30–20:00',
    phone:          '+49 89 4521-1609',
    description:    'Modische Basics und Trendteile für die ganze Familie zu unschlagbaren Preisen. Damen, Herren, Kinder – immer aktuelle Saison.',
    current_promo:  '30% auf Sommerkollektion',
    promo_color:    '#4f46e5',
    is_open:        true,
    rating:         4.1,
    review_count:   143,
    tags:           ['Mode', 'Familie', 'Basics', 'Günstig'],
  },
  {
    id:             'mer_017',
    name:           'Royal Styles',
    icon:           '💈',
    category:       'Friseur & Beauty',
    category_color: '#9333ea',
    location:       'OG 1, Shop 11',
    floor:          'OG 1',
    hours:          'Mo–Sa 09:00–20:00',
    phone:          '+49 89 4521-1711',
    description:    'Premium Friseur für Damen und Herren: Schnitte, Colorationen, Keratin-Behandlung und Styling. Ohne Termin willkommen.',
    current_promo:  '10% Rabatt für ZAM-Club-Mitglieder',
    promo_color:    '#9333ea',
    is_open:        true,
    rating:         4.6,
    review_count:   178,
    tags:           ['Friseur', 'Coloration', 'Styling', 'Herren'],
  },
  {
    id:             'mer_018',
    name:           'dm',
    icon:           '🧴',
    category:       'Drogerie',
    category_color: '#ca8a04',
    location:       'EG, Shop 01',
    floor:          'EG',
    hours:          'Mo–Sa 08:00–20:00',
    phone:          '+49 89 4521-1801',
    description:    'Drogerie dm mit Kosmetik, Naturpflege, Baby, Foto, Haushalt und Biolebensmitteln – Deutschlands beliebteste Drogerie.',
    current_promo:  'Doppelte Punkte auf dm-Eigenmarken',
    promo_color:    '#ca8a04',
    is_open:        true,
    rating:         4.5,
    review_count:   374,
    tags:           ['Drogerie', 'Kosmetik', 'Bio', 'Baby', 'Foto'],
  },
  {
    id:             'mer_019',
    name:           "L'Osteria",
    icon:           '🍕',
    category:       'Restaurant',
    category_color: '#ef4444',
    location:       'OG 1, Restaurant-Bereich',
    floor:          'OG 1',
    hours:          'Mo–So 11:00–23:00',
    phone:          '+49 89 4521-1901',
    description:    "L'Osteria – legendäre Pizzen mit riesigen Rand-Überhängern, hausgemachte Pasta und typisch italienische Antipasti. La dolce vita im ZAM.",
    current_promo:  '2. Pizza 50 % günstiger',
    promo_color:    '#ef4444',
    is_open:        true,
    rating:         4.6,
    review_count:   489,
    tags:           ['Pizza', 'Pasta', 'Italienisch', 'Familien'],
  },
  {
    id:             'mer_020',
    name:           'Katzentempel',
    icon:           '🐱',
    category:       'Café & Erlebnis',
    category_color: '#d97706',
    location:       'OG 2, Shop 22',
    floor:          'OG 2',
    hours:          'Di–So 11:00–20:00',
    phone:          '+49 89 4521-2022',
    description:    'Das einzigartige Katzencafé im ZAM: vegane und vegetarische Speisen, Kaffee und süße Gäste auf vier Pfoten. Entspannen mit Katzen.',
    current_promo:  'Gratis Stück Kuchen für Club-Mitglieder',
    promo_color:    '#d97706',
    is_open:        true,
    rating:         4.9,
    review_count:   532,
    tags:           ['Katzen', 'Vegan', 'Erlebnis', 'Café'],
  },
  {
    id:             'mer_021',
    name:           'NKD',
    icon:           '🧥',
    category:       'Mode & Textilien',
    category_color: '#0891b2',
    location:       'EG, Shop 08',
    floor:          'EG',
    hours:          'Mo–Sa 09:30–20:00',
    phone:          '+49 89 4521-2108',
    description:    'Mode und Heimtextilien zu Bestpreisen. Saisonale Kollektionen für die ganze Familie, Wäsche, Socken und Dekoration.',
    current_promo:  '20% auf Wohntextilien',
    promo_color:    '#0891b2',
    is_open:        true,
    rating:         3.9,
    review_count:   118,
    tags:           ['Mode', 'Haushalt', 'Familie', 'Günstig'],
  },
  {
    id:             'mer_022',
    name:           "Ernsting's Family",
    icon:           '👶',
    category:       'Kindermode',
    category_color: '#0284c7',
    location:       'EG, Shop 10',
    floor:          'EG',
    hours:          'Mo–Sa 09:30–20:00',
    phone:          '+49 89 4521-2210',
    description:    'Bunte Kindermode für 0–14 Jahre zu fairen Preisen. Tops, Hosen, Jacken, Schlafanzüge und Accessoires für jeden Anlass.',
    current_promo:  '3-für-2 auf Kinderoutfits',
    promo_color:    '#0284c7',
    is_open:        true,
    rating:         4.2,
    review_count:   141,
    tags:           ['Kinder', 'Baby', 'Mode', 'Familie'],
  },
  {
    id:             'mer_023',
    name:           'Fit Star',
    icon:           '💪',
    category:       'Sport & Fitness',
    category_color: '#10b981',
    location:       'OG 3, gesamte Etage',
    floor:          'OG 3',
    hours:          'Mo–Fr 06:00–23:00, Sa–So 08:00–21:00',
    phone:          '+49 89 4521-2330',
    description:    'Modernes Fitnessstudio mit 200+ Geräten, 30+ Kursformaten, Sauna und zertifizierten Personal Trainern. Münchens beliebtester Fitness-Hub.',
    current_promo:  '7 Tage kostenlos trainieren',
    promo_color:    '#10b981',
    is_open:        true,
    rating:         4.7,
    review_count:   612,
    tags:           ['Gym', 'Yoga', 'Sauna', 'Kurse', 'Personal Training'],
  },
  {
    id:             'mer_024',
    name:           'Vinzenzmurr',
    icon:           '🥩',
    category:       'Metzgerei & Feinkost',
    category_color: '#b91c1c',
    location:       'EG, Shop 06',
    floor:          'EG',
    hours:          'Mo–Sa 07:30–19:30',
    phone:          '+49 89 4521-2406',
    description:    'Bayerische Metzgerei mit Tradition: Frischfleisch, Wurst, Leberkäse, fertige Gerichte und Feinkostspezialitäten aus der Region.',
    current_promo:  'Leberkässemmel 2,20 € für Club-Mitglieder',
    promo_color:    '#b91c1c',
    is_open:        true,
    rating:         4.8,
    review_count:   289,
    tags:           ['Metzgerei', 'Bayern', 'Leberkäse', 'Regional'],
  },
  {
    id:             'mer_025',
    name:           'O2 Shop',
    icon:           '📱',
    category:       'Telekommunikation',
    category_color: '#2563eb',
    location:       'EG, Shop 11',
    floor:          'EG',
    hours:          'Mo–Sa 10:00–20:00',
    phone:          '+49 89 4521-2511',
    description:    'O2 Fachhandel für Smartphones, Tarife, Zubehör und persönliche Beratung. Jetzt mit 5G-Portfolio und Club-exklusiven Angeboten.',
    current_promo:  'Gratis Handyhülle bei Tarifabschluss',
    promo_color:    '#2563eb',
    is_open:        true,
    rating:         4.2,
    review_count:   132,
    tags:           ['Handy', 'Tarife', '5G', 'Zubehör'],
  },
  {
    id:             'mer_026',
    name:           'Club Pilates',
    icon:           '🧘',
    category:       'Sport & Wellness',
    category_color: '#7c3aed',
    location:       'OG 2, Shop 24',
    floor:          'OG 2',
    hours:          'Mo–Fr 07:00–21:00, Sa–So 09:00–17:00',
    phone:          '+49 89 4521-2624',
    description:    'Boutique-Pilates-Studio mit Reformer-Equipment und kleinen Gruppen für maximale Aufmerksamkeit. Für Einsteiger und Fortgeschrittene.',
    current_promo:  'Erststunde gratis für ZAM-Club-Mitglieder',
    promo_color:    '#7c3aed',
    is_open:        true,
    rating:         4.9,
    review_count:   156,
    tags:           ['Pilates', 'Reformer', 'Wellness', 'Kleine Gruppen'],
  },
  {
    id:             'mer_027',
    name:           'TK Maxx',
    icon:           '🛍️',
    category:       'Mode & Lifestyle',
    category_color: '#dc2626',
    location:       'OG 1, Shop 15',
    floor:          'OG 1',
    hours:          'Mo–Sa 09:30–20:00',
    phone:          '+49 89 4521-2715',
    description:    'Markenmode, Homeware, Schuhe und Accessoires zu bis zu 60% unter dem UVP. Jeden Tag neue Lieferungen – jeden Tag neues Entdecken.',
    current_promo:  '10% extra Rabatt für Club-Mitglieder',
    promo_color:    '#dc2626',
    is_open:        true,
    rating:         4.4,
    review_count:   367,
    tags:           ['Marken', 'Rabatt', 'Mode', 'Homeware'],
  },
  {
    id:             'mer_028',
    name:           'Star Friseur',
    icon:           '✂️',
    category:       'Friseur',
    category_color: '#0891b2',
    location:       'EG, Shop 13',
    floor:          'EG',
    hours:          'Mo–Sa 09:00–20:00',
    phone:          '+49 89 4521-2813',
    description:    'Schneller Friseur ohne Termin: Damenschnitt, Herrenschnitt, Kinderschnitt. Immer faire Preise, kurze Wartezeiten.',
    current_promo:  'Herrenschnitt 12 € für Club-Mitglieder',
    promo_color:    '#0891b2',
    is_open:        true,
    rating:         4.1,
    review_count:   97,
    tags:           ['Friseur', 'Schnitt', 'Ohne Termin', 'Günstig'],
  },
  {
    id:             'mer_029',
    name:           'Döner Baum',
    icon:           '🥙',
    category:       'Türkische Küche',
    category_color: '#d97706',
    location:       'Food Court, OG 1',
    floor:          'OG 1',
    hours:          'Mo–So 10:00–22:00',
    phone:          '+49 89 4521-2901',
    description:    'Frische Döner, Lahmacun, Falafel-Wrap und Ayran. Alles frisch zubereitet mit Fleisch vom Spieß und Gemüse der Saison.',
    current_promo:  'Gratis Getränk zum Menü',
    promo_color:    '#d97706',
    is_open:        true,
    rating:         4.5,
    review_count:   263,
    tags:           ['Döner', 'Türkisch', 'Halal', 'Wrap'],
  },
  {
    id:             'mer_030',
    name:           'Apotheke im ZAM',
    icon:           '🏥',
    category:       'Gesundheit',
    category_color: '#16a34a',
    location:       'EG, Shop 02',
    floor:          'EG',
    hours:          'Mo–Sa 08:00–20:00',
    phone:          '+49 89 4521-3002',
    description:    'Vollsortiment-Apotheke mit Beratung, Rezeptservice, Impfberatung und breiter Auswahl an OTC-Produkten und Naturheilmitteln.',
    current_promo:  'Gratis Vitamin-D-Test für Mitglieder',
    promo_color:    '#16a34a',
    is_open:        true,
    rating:         4.7,
    review_count:   219,
    tags:           ['Apotheke', 'Rezept', 'Naturheilkunde', 'Beratung'],
  },
  {
    id:             'mer_031',
    name:           'ALDI',
    icon:           '🛒',
    category:       'Supermarkt',
    category_color: '#1d4ed8',
    location:       'EG, Westflügel',
    floor:          'EG',
    hours:          'Mo–Sa 07:30–21:00',
    phone:          '+49 89 4521-3101',
    description:    'ALDI Süd mit frischem Obst und Gemüse, Bäckerei, wöchentlichen Aktionsangeboten und breitem Lebensmittelsortiment.',
    current_promo:  '30 Punkte bei Einkauf über 20 €',
    promo_color:    '#1d4ed8',
    is_open:        true,
    rating:         4.1,
    review_count:   431,
    tags:           ['Supermarkt', 'Günstig', 'Frisch', 'Aktionen'],
  },
  {
    id:             'mer_032',
    name:           'CleverDrive Fahrschule',
    icon:           '🚗',
    category:       'Fahrschule & Services',
    category_color: '#0284c7',
    location:       'OG 2, Shop 21',
    floor:          'OG 2',
    hours:          'Mo–Fr 09:00–18:00, Sa 09:00–13:00',
    phone:          '+49 89 4521-3221',
    description:    'Moderne Fahrschule mit App-Theorie, flexiblen Fahrstunden und günstigen Club-Paketen. B, BE, AM – alles aus einer Hand.',
    current_promo:  '1 Fahrstunde gratis für Neukunden',
    promo_color:    '#0284c7',
    is_open:        true,
    rating:         4.6,
    review_count:   88,
    tags:           ['Fahrschule', 'Führerschein', 'Flexibel', 'App'],
  },
  {
    id:             'mer_033',
    name:           'Sparkasse',
    icon:           '🏦',
    category:       'Bank & Finanzen',
    category_color: '#dc2626',
    location:       'EG, Shop 01',
    floor:          'EG',
    hours:          'Mo–Fr 09:00–17:00',
    phone:          '+49 89 4521-3301',
    description:    'Sparkasse Filiale mit persönlicher Beratung, Kontoservice, Geldautomat und Beratung für Finanzierungen und Altersvorsorge.',
    current_promo:  'Gratis Girokonto für ZAM-Club-Mitglieder',
    promo_color:    '#dc2626',
    is_open:        true,
    rating:         4.0,
    review_count:   74,
    tags:           ['Bank', 'Konto', 'Beratung', 'ATM'],
  },
  {
    id:             'mer_034',
    name:           'Brotmanufaktur',
    icon:           '🍞',
    category:       'Bäckerei',
    category_color: '#92400e',
    location:       'EG, Eingang Nord',
    floor:          'EG',
    hours:          'Mo–Sa 06:30–19:00, So 07:30–17:00',
    phone:          '+49 89 4521-3401',
    description:    'Handwerkliche Bäckerei mit täglich frischem Sauerteigbrot, Brötchen, Croissants und süßen Teilchen aus echter Handarbeit.',
    current_promo:  'Gratis Brötchen zum Kaffee',
    promo_color:    '#92400e',
    is_open:        true,
    rating:         4.9,
    review_count:   387,
    tags:           ['Bäckerei', 'Sauerteig', 'Bio', 'Handwerk'],
  },
  {
    id:             'mer_035',
    name:           'Annam Grill',
    icon:           '🍜',
    category:       'Vietnamesische Küche',
    category_color: '#059669',
    location:       'Food Court, OG 1',
    floor:          'OG 1',
    hours:          'Mo–So 11:00–21:30',
    phone:          '+49 89 4521-3501',
    description:    'Vietnamesische Grillspezialitäten: Bún bò Huế, Bánh mì, Phở und frische Sommers-Rollen. Alles frisch zubereitet nach Originalrezepten.',
    current_promo:  'Gratis Sommerrolle zum Hauptgericht',
    promo_color:    '#059669',
    is_open:        true,
    rating:         4.7,
    review_count:   174,
    tags:           ['Vietnamesisch', 'Pho', 'Grill', 'Frisch'],
  },
];

// ============================================================
// TABLE: events
// Supabase: public.events
// ============================================================
const events = [
  {
    id:             'evt_001',
    title:          'ZAM Sommermarkt 2026',
    category:       'Food & Lifestyle',
    category_color: '#f59e0b',
    date_iso:       '2026-06-21',
    date_formatted: 'Sa, 21. Juni 2026',
    time_start:     '10:00',
    time_end:       '19:00',
    time:           '10:00 – 19:00 Uhr',
    location:       'Vorplatz ZAM, Außenbereich',
    merchant_id:    null,
    description:    'Das größte Freiham-Event des Jahres! Regionale Foodtrucks, Live-Musik und über 40 Aussteller. Mit dabei: Café Müller, Brotmanufaktur, Vinzenzmurr und Annam Grill. Kinderbereich mit Smyths Toys. Eintritt frei – ZAM-Club-Mitglieder erhalten +80 Punkte beim Check-in!',
    spots_total:    999,
    spots_left:     999,
    points_reward:  80,
    is_featured:    true,
    image_url:      null,
  },
  {
    id:             'evt_002',
    title:          'Food Festival im ZAM',
    category:       'Food & Drinks',
    category_color: '#ef4444',
    date_iso:       '2026-06-28',
    date_formatted: 'So, 28. Juni 2026',
    time_start:     '12:00',
    time_end:       '20:00',
    time:           '12:00 – 20:00 Uhr',
    location:       'Food Court OG 1, gesamte Etage',
    merchant_id:    null,
    description:    "Alle ZAM-Restaurants gemeinsam feiern: KFC, Dunkin Donuts, Subway, L'Osteria, Döner Baum, Asia Street Food, Annam Grill, Sunhye und Pit's Stop Burger präsentieren Sondergerichte. Club-Mitglieder erhalten +50 Punkte und ein Gratis-Getränk beim Check-in.",
    spots_total:    800,
    spots_left:     612,
    points_reward:  50,
    is_featured:    true,
    image_url:      null,
  },
  {
    id:             'evt_003',
    title:          'Kinderaktion mit Smyths Toys',
    category:       'Familie & Kinder',
    category_color: '#16a34a',
    date_iso:       '2026-07-05',
    date_formatted: 'Sa, 5. Juli 2026',
    time_start:     '11:00',
    time_end:       '17:00',
    time:           '11:00 – 17:00 Uhr',
    location:       'Smyths Toys, OG 2',
    merchant_id:    'mer_010',
    description:    'Ein Tag voller Spaß für Kinder: LEGO-Baumeisterwettbewerb, Gaming-Turnier, Verkleidungsaktion und Gratis-Überraschungen. Für alle Kinder bis 14 Jahre. Eintritt frei – Eltern zahlen keinen Eintritt.',
    spots_total:    200,
    spots_left:     143,
    points_reward:  60,
    is_featured:    false,
    image_url:      null,
  },
  {
    id:             'evt_004',
    title:          'Fit Star Open Day',
    category:       'Sport & Fitness',
    category_color: '#10b981',
    date_iso:       '2026-07-12',
    date_formatted: 'Sa, 12. Juli 2026',
    time_start:     '09:00',
    time_end:       '16:00',
    time:           '09:00 – 16:00 Uhr',
    location:       'Fit Star, OG 3',
    merchant_id:    'mer_023',
    description:    'Fit Star öffnet seine Türen: kostenlose Probekurse (Yoga, HIIT, Zumba), persönliche Trainingsberatung und Ernährungsworkshop. Club-Mitglieder erhalten +40 Punkte und ein exklusives Fitnesspaket.',
    spots_total:    150,
    spots_left:     87,
    points_reward:  40,
    is_featured:    false,
    image_url:      null,
  },
  {
    id:             'evt_005',
    title:          'TK Maxx Shopping Night',
    category:       'Shopping & Mode',
    category_color: '#dc2626',
    date_iso:       '2026-07-18',
    date_formatted: 'Fr, 18. Juli 2026',
    time_start:     '18:00',
    time_end:       '22:00',
    time:           '18:00 – 22:00 Uhr',
    location:       'TK Maxx, OG 1',
    merchant_id:    'mer_027',
    description:    'Exklusive ZAM-Club-Shoppingnacht bei TK Maxx: 15% extra Rabatt für alle Mitglieder, Prosecco-Empfang, persönliche Styling-Beratung und Verlosung hochwertiger Markenprodukte.',
    spots_total:    100,
    spots_left:     34,
    points_reward:  70,
    is_featured:    true,
    image_url:      null,
  },
];

// ============================================================
// TABLE: deals
// Supabase: public.deals
// ============================================================
const deals = [
  {
    id:               'deal_001',
    merchant_id:      'mer_002',
    store_name:       'KFC',
    store_icon:       '🍗',
    category:         'Fast Food',
    category_color:   '#dc2626',
    discount:         'Gratis',
    title:            '2 Hot Wings gratis ab 10 €',
    description:      'Bestelle für mindestens 10 € bei KFC im ZAM und erhalte 2 knusprige Hot Wings gratis dazu. Einfach App zeigen, Bestellung aufgeben, Bonus sichern.',
    expiry_date:      '2026-06-30',
    expiry_formatted: 'Gültig bis 30. Juni 2026',
    points_reward:    40,
    is_hot:           true,
    barcode:          '2201-5588-9910',
    image_url:        null,
  },
  {
    id:               'deal_002',
    merchant_id:      'mer_008',
    store_name:       'Dunkin Donuts',
    store_icon:       '🍩',
    category:         'Café & Snacks',
    category_color:   '#f97316',
    discount:         'Gratis',
    title:            'Gratis Donut zum Kaffee',
    description:      'Kauf einen Kaffee deiner Wahl bei Dunkin Donuts und such dir einen Donut aus unserer Klassiker-Auswahl gratis dazu aus. Täglich verfügbar, solange der Vorrat reicht.',
    expiry_date:      '2026-06-25',
    expiry_formatted: 'Gültig bis 25. Juni 2026',
    points_reward:    30,
    is_hot:           true,
    barcode:          '8843-1190-4430',
    image_url:        null,
  },
  {
    id:               'deal_003',
    merchant_id:      'mer_019',
    store_name:       "L'Osteria",
    store_icon:       '🍕',
    category:         'Restaurant',
    category_color:   '#ef4444',
    discount:         '50%',
    title:            '2. Pizza 50 % günstiger',
    description:      "Zu zweit essen bei L'Osteria? Bestell zwei Pizzen und die günstigere gibt es für die Hälfte! Gilt auf alle Pizzen der regulären Karte. Kein Mindestumsatz, kein Stress.",
    expiry_date:      '2026-06-22',
    expiry_formatted: 'Gültig bis 22. Juni 2026',
    points_reward:    60,
    is_hot:           true,
    barcode:          '3310-8821-5547',
    image_url:        null,
  },
  {
    id:               'deal_004',
    merchant_id:      'mer_023',
    store_name:       'Fit Star',
    store_icon:       '💪',
    category:         'Sport & Fitness',
    category_color:   '#10b981',
    discount:         '7 Tage',
    title:            '7 Tage kostenlos trainieren',
    description:      'Teste Fit Star eine ganze Woche lang gratis – alle 200+ Geräte, alle Kursformate, Sauna inklusive. Kein Abo, kein Risiko, einfach mit der ZAM-Club-App reinkommen.',
    expiry_date:      '2026-06-30',
    expiry_formatted: 'Gültig bis 30. Juni 2026',
    points_reward:    100,
    is_hot:           true,
    barcode:          '9901-2255-8843',
    image_url:        null,
  },
  {
    id:               'deal_005',
    merchant_id:      'mer_027',
    store_name:       'TK Maxx',
    store_icon:       '🛍️',
    category:         'Mode & Lifestyle',
    category_color:   '#dc2626',
    discount:         '10%',
    title:            '10 % auf ausgewählte Artikel',
    description:      'ZAM-Club-Mitglieder erhalten 10% extra Rabatt auf bereits reduzierte Markenartikel bei TK Maxx. Gilt auf Kleidung, Schuhe, Homeware und Accessoires. Einfach App vorzeigen.',
    expiry_date:      '2026-07-05',
    expiry_formatted: 'Gültig bis 5. Juli 2026',
    points_reward:    50,
    is_hot:           false,
    barcode:          '7721-0033-8854',
    image_url:        null,
  },
  {
    id:               'deal_006',
    merchant_id:      'mer_015',
    store_name:       'Asia Street Food',
    store_icon:       '🥢',
    category:         'Asiatische Küche',
    category_color:   '#065f46',
    discount:         'Gratis',
    title:            'Gratis Frühlingsrollen zum Hauptgericht',
    description:      '2 hausgemachte Frühlingsrollen gratis bei Bestellung eines Hauptgerichts. Frisch aus dem Wok, täglich zubereitet. Einlösbar beim Asia Street Food Stand im Food Court.',
    expiry_date:      '2026-06-23',
    expiry_formatted: 'Gültig bis 23. Juni 2026',
    points_reward:    35,
    is_hot:           false,
    barcode:          '4490-2211-3387',
    image_url:        null,
  },
  {
    id:               'deal_007',
    merchant_id:      'mer_029',
    store_name:       'Döner Baum',
    store_icon:       '🥙',
    category:         'Türkische Küche',
    category_color:   '#d97706',
    discount:         'Gratis',
    title:            'Gratis Getränk zum Menü',
    description:      'Bestell beim Döner Baum ein Menü (Döner + Beilage) und such dir ein Getränk deiner Wahl gratis aus. Gilt auf alle Softdrinks und Ayran. Täglich verfügbar.',
    expiry_date:      '2026-06-28',
    expiry_formatted: 'Gültig bis 28. Juni 2026',
    points_reward:    25,
    is_hot:           false,
    barcode:          '6612-9934-1120',
    image_url:        null,
  },
  {
    id:               'deal_008',
    merchant_id:      'mer_012',
    store_name:       "Pit's Stop Burger",
    store_icon:       '🍔',
    category:         'Burger & Fast Food',
    category_color:   '#b45309',
    discount:         '2 für 1',
    title:            '2 Burger zum Preis von 1 – nur heute!',
    description:      "Hol dir zwei Signature Burger bei Pit's Stop Burger und zahl nur einen. Gilt auf alle Burger der Karte. Einfach Bon in der ZAM App zeigen.",
    expiry_date:      '2026-07-31',
    expiry_formatted: 'Gültig bis 31. Juli 2026',
    points_reward:    60,
    is_hot:           true,
    barcode:          '9901-2345-6780',
    image_url:        null,
    media_type:       'video',
    media_url:        'https://www.w3schools.com/html/mov_bbb.mp4',
    media_thumbnail:  null,
  },
  {
    id:               'deal_009',
    merchant_id:      'mer_008',
    store_name:       'Dunkin Donuts',
    store_icon:       '🍩',
    category:         'Café & Snacks',
    category_color:   '#f97316',
    discount:         '20% Rabatt',
    title:            'Neue Sommer-Kollektion – 20% auf alles',
    description:      'Schau dir unsere neuen Sommer-Donuts und Getränke an und sichere dir 20% Rabatt auf deinen gesamten Einkauf. Exklusiv für ZAM Club Mitglieder.',
    expiry_date:      '2026-08-15',
    expiry_formatted: 'Gültig bis 15. August 2026',
    points_reward:    35,
    is_hot:           false,
    barcode:          '8834-5512-0091',
    image_url:        null,
    media_type:       'instagram',
    media_url:        'https://www.instagram.com/reel/demo',
  },
];

// ============================================================
// TABLE: community_posts
// Supabase: public.community_posts  +  public.profiles (join)
// ============================================================
const communityPosts = [
  {
    id:         'post_001',
    user_id:    'usr_042',
    author: {
      name:         'Mia K.',
      initials:     'MK',
      avatar_color: '#7c3aed',
      level:        'Gold Member',
    },
    content:    'Der Sommermarkt war einfach ein Traum ☀️ Die Brotmanufaktur hatte das kross gebackenste Sauerteigbrot – und der Annam Grill hat mich mit seinen Pho-Varianten komplett umgehauen. Genau so soll ein Wochenende aussehen! Danke ZAM 💜',
    tags:       ['ZAMSommermarkt', 'Brotmanufaktur', 'AnnamGrill', 'FreihamLeben'],
    image_url:  null,
    likes:      61,
    comments:   9,
    created_at: '2026-06-15T08:30:00Z',
    time_ago:   'vor 1 Stunde',
    is_liked:   false,
  },
  {
    id:         'post_002',
    user_id:    'usr_017',
    author: {
      name:         'Felix B.',
      initials:     'FB',
      avatar_color: '#10b981',
      level:        'Silber Member',
    },
    content:    'Erststunde bei Club Pilates heute ausprobiert – und direkt ein Abo abgeschlossen 😅 Reformer-Pilates im kleinen Kurs mit echtem Fokus auf mich. Nach dem Training war ich bei Dunkin Donuts und hatte mir den Donut mehr als verdient 🍩 Der Deal aus der App hat geklappt!',
    tags:       ['ClubPilates', 'DunkinDonuts', 'ZAMDeals', 'Freiham'],
    image_url:  null,
    likes:      38,
    comments:   6,
    created_at: '2026-06-14T09:15:00Z',
    time_ago:   'vor 23 Stunden',
    is_liked:   false,
  },
  {
    id:         'post_003',
    user_id:    'usr_088',
    author: {
      name:         'Sarah L.',
      initials:     'SL',
      avatar_color: '#ec4899',
      level:        'Platin Member',
    },
    content:    'Mittagstipp für alle Foodie-Club-Mitglieder: Heute Sunhye ausprobiert – Bibimbap-Bowl war unfassbar frisch. Danach kurz bei Café Müller Kaffee geholt und den Gratis-Donut bei Dunkin Donuts eingelöst. So macht Lunch-Pause Spaß 🍜☕🍩',
    tags:       ['Sunhye', 'CafeMüller', 'DunkinDonuts', 'ZAMDeals'],
    image_url:  null,
    likes:      54,
    comments:   12,
    created_at: '2026-06-13T13:00:00Z',
    time_ago:   'gestern',
    is_liked:   true,
  },
  {
    id:         'post_004',
    user_id:    'usr_031',
    author: {
      name:         'Tom W.',
      initials:     'TW',
      avatar_color: '#f59e0b',
      level:        'Gold Member',
    },
    content:    '7 Tage Fit Star über den ZAM-Club-Deal ausprobiert – und direkt eine Jahresmitgliedschaft abgeschlossen 😅 Die Kursauswahl ist wahnsinnig und die Trainer sind top. Wer noch überlegt: einfach machen, lohnt sich 100%!',
    tags:       ['FitStar', 'ZAMClub', 'Fitnessziele', 'Freiham'],
    image_url:  null,
    likes:      47,
    comments:   8,
    created_at: '2026-06-12T18:30:00Z',
    time_ago:   'vor 2 Tagen',
    is_liked:   false,
  },
  {
    id:         'post_005',
    user_id:    'usr_055',
    author: {
      name:         'Anna P.',
      initials:     'AP',
      avatar_color: '#3b82f6',
      level:        'Silber Member',
    },
    content:    'Meine beiden (6 und 9) bei Smyths Toys gewesen – LEGO-Baustation und Gaming-Ecke haben sie komplett in den Bann gezogen 🧸 Danach Döner Baum für alle, Getränk war gratis mit dem Club-Deal. Perfekter Samstag in Freiham! 🥙',
    tags:       ['SmythsToys', 'DönerBaum', 'ZAMFamilie', 'FreihamKinder'],
    image_url:  null,
    likes:      39,
    comments:   5,
    created_at: '2026-06-11T17:00:00Z',
    time_ago:   'vor 4 Tagen',
    is_liked:   false,
  },
];

// ============================================================
// TABLE: spin_merchant_rewards
// Supabase: public.spin_merchant_rewards
// Händler können Gewinne für den Lucky Spin einreichen.
// ============================================================
const spinMerchantRewards = [
  {
    id:                  'spr_001',
    merchant_id:         'mer_008',
    merchant_name:       'Dunkin Donuts',
    merchant_icon:       '🍩',
    banner_color:        '#ea580c',
    title:               'Gratis Donut',
    description:         'Einen Donut deiner Wahl gratis – direkt bei Dunkin Donuts im ZAM Erdgeschoss einlösbar. Klassiker, Glazed oder Seasonal.',
    reward_type:         'gratis_product',
    total_quantity:      12,
    remaining_quantity:  9,
    active_from:         '2026-06-16',
    active_until:        '2026-06-30',
    redeem_within_days:  14,
    terms:               'Gilt für 1 Standard-Donut. Nicht mit anderen Aktionen kombinierbar.',
    status:              'approved',
    probability:         0.04,
  },
  {
    id:                  'spr_002',
    merchant_id:         'mer_001',
    merchant_name:       'Café Müller',
    merchant_icon:       '☕',
    banner_color:        '#b45309',
    title:               'Gratis Kaffee',
    description:         'Ein Kaffee deiner Wahl gratis bei Café Müller. Gilt auf alle Kaffee-Spezialitäten inklusive Oat-Milk-Varianten.',
    reward_type:         'gratis_product',
    total_quantity:      8,
    remaining_quantity:  6,
    active_from:         '2026-06-16',
    active_until:        '2026-06-30',
    redeem_within_days:  14,
    terms:               'Gilt für 1 Heißgetränk (max. Wert 5,50 €). Täglich 07:30–11:00.',
    status:              'approved',
    probability:         0.035,
  },
  {
    id:                  'spr_003',
    merchant_id:         'mer_015',
    merchant_name:       'Asia Street Food',
    merchant_icon:       '🥢',
    banner_color:        '#065f46',
    title:               'Gratis Frühlingsrollen',
    description:         '2 hausgemachte Frühlingsrollen gratis zum Hauptgericht. Im Food Court OG 1 einlösbar.',
    reward_type:         'gratis_product',
    total_quantity:      5,
    remaining_quantity:  3,
    active_from:         '2026-06-16',
    active_until:        '2026-06-23',
    redeem_within_days:  7,
    terms:               '2 Frühlingsrollen gratis bei Kauf eines Hauptgerichts. Einmalig pro Person.',
    status:              'approved',
    probability:         0.03,
  },
  {
    id:                  'spr_004',
    merchant_id:         'mer_020',
    merchant_name:       'Katzentempel',
    merchant_icon:       '🐱',
    banner_color:        '#d97706',
    title:               'Gratis Stück Kuchen',
    description:         'Ein Stück veganer Kuchen deiner Wahl gratis im Katzentempel – natürlich in Gesellschaft der pelzigen Bewohner.',
    reward_type:         'gratis_product',
    total_quantity:      6,
    remaining_quantity:  4,
    active_from:         '2026-06-16',
    active_until:        '2026-06-30',
    redeem_within_days:  14,
    terms:               '1 Stück Kuchen gratis. Tischreservierung empfohlen. Di–So.',
    status:              'approved',
    probability:         0.025,
  },
  {
    id:                  'spr_005',
    merchant_id:         'mer_027',
    merchant_name:       'TK Maxx',
    merchant_icon:       '🛍️',
    banner_color:        '#dc2626',
    title:               '10 % Gutschein',
    description:         'Exklusiver Spin-Gewinn: 10% Rabatt-Coupon für TK Maxx. Auf Kleidung, Schuhe, Homeware – alles bereits reduziert, jetzt noch günstiger.',
    reward_type:         'discount',
    total_quantity:      4,
    remaining_quantity:  4,
    active_from:         '2026-06-16',
    active_until:        '2026-07-05',
    redeem_within_days:  10,
    terms:               '10% auf reguläre reduzierte Ware. Einmalig einlösbar. Nicht kombinierbar.',
    status:              'approved',
    probability:         0.02,
  },
  {
    id:                  'spr_006',
    merchant_id:         'mer_034',
    merchant_name:       'Brotmanufaktur',
    merchant_icon:       '🍞',
    banner_color:        '#92400e',
    title:               'Gratis Brötchen',
    description:         '2 frische Handwerks-Brötchen deiner Wahl gratis bei der Brotmanufaktur im ZAM. Täglich frisch gebacken.',
    reward_type:         'gratis_product',
    total_quantity:      10,
    remaining_quantity:  8,
    active_from:         '2026-06-16',
    active_until:        '2026-06-30',
    redeem_within_days:  7,
    terms:               '2 Brötchen gratis, solange der Vorrat reicht. Mo–Sa.',
    status:              'approved',
    probability:         0.03,
  },
  {
    id:                  'spr_007',
    merchant_id:         'mer_035',
    merchant_name:       'Annam Grill',
    merchant_icon:       '🍜',
    banner_color:        '#059669',
    title:               'Gratis Sommerrolle',
    description:         '1 frische vietnamesische Sommerrolle gratis zum Hauptgericht bei Annam Grill. Frisch gerollt, leicht und lecker.',
    reward_type:         'gratis_product',
    total_quantity:      6,
    remaining_quantity:  5,
    active_from:         '2026-06-16',
    active_until:        '2026-06-26',
    redeem_within_days:  10,
    terms:               '1 Sommerrolle gratis bei Bestellung eines Hauptgerichts. Pro Person einmalig.',
    status:              'approved',
    probability:         0.025,
  },
];

// ============================================================
// TABLE: spin_rewards  (config table)
// Supabase: public.spin_rewards
// ============================================================
const spinRewards = [
  { id: 'spin_001', label: '10 Punkte',      points: 10,  probability: 0.30 },
  { id: 'spin_002', label: '25 Punkte',      points: 25,  probability: 0.28 },
  { id: 'spin_003', label: '50 Punkte',      points: 50,  probability: 0.22 },
  { id: 'spin_004', label: '100 Punkte',     points: 100, probability: 0.12 },
  { id: 'spin_005', label: '250 Punkte',     points: 250, probability: 0.06 },
  { id: 'spin_006', label: '🎉 Jackpot 500', points: 500, probability: 0.02 },
];

// ============================================================
// TABLE: challenges (monthly)
// ============================================================
const challenges = [
  { id: 'ch_001', title: 'Händler-Entdecker',  description: 'Checke bei 3 verschiedenen Händlern ein', icon: '🏪', target: 3, stat: 'visits',          reward_pts: 100 },
  { id: 'ch_002', title: 'Deal-Sammler',        description: 'Speichere oder sichere 5 Deals',          icon: '🏷️', target: 5, stat: 'deals_saved',     reward_pts: 150 },
  { id: 'ch_003', title: 'Event-Fan',           description: 'Nimm an 2 Events teil',                   icon: '🎟️', target: 2, stat: 'events_attended', reward_pts: 120 },
  { id: 'ch_004', title: 'Community-Starter',   description: 'Teile deinen ersten Beitrag',              icon: '💬', target: 1, stat: 'posts_created',   reward_pts:  75 },
  { id: 'ch_005', title: 'Spin-Profi',          description: '5× am Glücksrad drehen',                  icon: '🎰', target: 5, stat: 'spins',            reward_pts:  80 },
];

// ============================================================
// Global namespace
// Supabase-Migration: ersetze jeden Wert durch einen API-Call.
//
// Beispiel (später):
//   ZAMData.events = (await supabase.from('events').select('*')).data;
// ============================================================
window.ZAMData = {
  currentUser,            // → supabase.auth.getUser()  +  profiles.select()
  profiles,               // → supabase.from('profiles').select()
  badges,                 // → supabase.from('badges').select() + user_badges join
  merchants,              // → supabase.from('merchants').select()
  events,                 // → supabase.from('events').select()
  deals,                  // → supabase.from('deals').select()
  communityPosts,         // → supabase.from('community_posts').select('*, profiles(*)')
  spinRewards,            // → supabase.from('spin_rewards').select()
  spinMerchantRewards,    // → supabase.from('spin_merchant_rewards').select()
  challenges,             // → supabase.from('challenges').select()
};
